name: Views Validation

on:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Framework
        uses: actions/checkout@v3
        with:
          path: framework
      - name: Checkout Views
        uses: actions/checkout@v3
        with:
          path: views
          repository: vitruv-tools/Vitruv-Views
          ref: main
          fetch-depth: 0
      - name: Checkout Matching Views Branch
        run: |
          cd views
          git checkout -B ${{ github.head_ref }} origin/${{ github.head_ref }} || true
      - name: Cache
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/MANIFEST.MF') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11
      - name: Build Framework
        working-directory: ./framework
        run: >
          ./mvnw -B -U package -Dmaven.test.skip=true
          -Dstyle.color=always
          -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
          -Dorg.slf4j.simpleLogger.log.org.eclipse.tycho.core.resolver.DefaultTychoResolver=warn
          -Dorg.slf4j.simpleLogger.log.org.eclipse.tycho.osgi.configuration.MavenContextConfigurator=warn
          -Dorg.slf4j.simpleLogger.log.org.eclipse.sisu.equinox.launching.internal.DefaultEquinoxLauncher=warn
          -Dorg.slf4j.simpleLogger.log.org.eclipse.xtext.maven.XtextGenerateMojo=warn
          -Dorg.apache.commons.logging.Log=org.apache.commons.logging.impl.NoOpLog
        env: 
          MAVEN_OPTS: -Djansi.force=true
      - name: Build Views
        uses: GabrielBB/xvfb-action@v1
        with:
          working-directory: ./views
          run: >
            ./mvnw -B -U clean verify
            -Dvitruv.framework.path=${GITHUB_WORKSPACE}/framework
            -Dstyle.color=always
            -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
            -Dorg.slf4j.simpleLogger.log.org.eclipse.tycho.core.resolver.DefaultTychoResolver=warn
            -Dorg.slf4j.simpleLogger.log.org.eclipse.tycho.osgi.configuration.MavenContextConfigurator=warn
            -Dorg.slf4j.simpleLogger.log.org.eclipse.sisu.equinox.launching.internal.DefaultEquinoxLauncher=warn
            -Dorg.slf4j.simpleLogger.log.org.eclipse.xtext.maven.XtextGenerateMojo=warn
            -Dorg.apache.commons.logging.Log=org.apache.commons.logging.impl.NoOpLog
        env: 
          MAVEN_OPTS: -Djansi.force=true
